name: "Pact mark as deployed to production"
description: "Marks the current version as deployed to production in the pact broker"

inputs:
  pacticipant-name:
    description: "The name of the consumer"
    required: true
  broker-url:
    description: "The URL to the pact broker"
    required: https://pact-broker.private.element.in
  broker-username:
    description: "The username for authenticating against the pact-broker"
  broker-password:
    description: "The password for authenticating against the pact-broker"

runs:
  using: "composite"
  steps:
    - name: Please remove me
      id: tags
      shell: bash
      run: |
        echo "No-op. Please do not use this anymore. We abandoned the use of pact tests"

    # - name: tag pacticipant version with prod
    #   shell: bash
    #   run: docker run --rm -e PACT_BROKER_USERNAME=$PACT_BROKER_USERNAME -e PACT_BROKER_PASSWORD=$PACT_BROKER_PASSWORD pactfoundation/pact-cli broker create-version-tag --pacticipant ${{ inputs.pacticipant-name }} --version ${GITHUB_SHA::7} --tag prod  --broker-base-url=${{ inputs.broker-url }}
    #   env:
    #     PACT_BROKER_USERNAME: ${{ inputs.broker-username }}
    #     PACT_BROKER_PASSWORD: ${{ inputs.broker-password }}
